pre-release-replacements = [
    { file = "CHANGELOG.md", search = "Unreleased", replace = "{{version}}"},
    { file = "CHANGELOG.md", search = "\\.\\.\\.HEAD", replace = "...v{{version}}"},
]
pre-release-commit-message = "chore(release): release {{version}}"
post-release-commit-message = "chore(release): starting {{next_version}}"